// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx41vjfetZnCz6JFkxL4IcnBevBC2lNdw',
    appId: '1:356745431301:web:c79d41e48d635b020e4f6c',
    messagingSenderId: '356745431301',
    projectId: 'todo-a6c5b',
    authDomain: 'todo-a6c5b.firebaseapp.com',
    storageBucket: 'todo-a6c5b.firebasestorage.app',
    measurementId: 'G-Y5N6F3ZK46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMnl-OJKgBC3ofWB2A1XXfTF6Wzc3v5w0',
    appId: '1:356745431301:android:4b699498cea3a0e10e4f6c',
    messagingSenderId: '356745431301',
    projectId: 'todo-a6c5b',
    storageBucket: 'todo-a6c5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAooXw433eScz0Lf47IbHohxKiHMX5LTHo',
    appId: '1:356745431301:ios:f8c58fbf28f7b6cd0e4f6c',
    messagingSenderId: '356745431301',
    projectId: 'todo-a6c5b',
    storageBucket: 'todo-a6c5b.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAooXw433eScz0Lf47IbHohxKiHMX5LTHo',
    appId: '1:356745431301:ios:f8c58fbf28f7b6cd0e4f6c',
    messagingSenderId: '356745431301',
    projectId: 'todo-a6c5b',
    storageBucket: 'todo-a6c5b.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx41vjfetZnCz6JFkxL4IcnBevBC2lNdw',
    appId: '1:356745431301:web:962a06ba436e4c850e4f6c',
    messagingSenderId: '356745431301',
    projectId: 'todo-a6c5b',
    authDomain: 'todo-a6c5b.firebaseapp.com',
    storageBucket: 'todo-a6c5b.firebasestorage.app',
    measurementId: 'G-86YYKF07NG',
  );
}
